name: Rounds
options:
  bundleIdPrefix: com.rounds
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    GENERATE_INFOPLIST_FILE: YES

targets:
  Rounds:
    type: application
    platform: iOS
    sources:
      - path: Rounds
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rounds.app
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Rounds needs microphone access to transcribe your conversations"
        INFOPLIST_KEY_NSSpeechRecognitionUsageDescription: "Rounds uses speech recognition to create live transcripts"
        INFOPLIST_KEY_NSBluetoothAlwaysUsageDescription: "Rounds connects to Meta glasses via Bluetooth"
        INFOPLIST_KEY_NSBluetoothPeripheralUsageDescription: "Rounds connects to Meta glasses via Bluetooth"
